version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_key
      - name: customer_id

  - name: dim_products
    columns:
      - name: product_key
      - name: product_id

  - name: fact_orders
    columns:
      - name: order_key
      - name: order_id
      - name: customer_id
      - name: customer_key

  - name: fact_order_items
    columns:
      - name: item_key
      - name: order_key
      - name: product_key
